apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ponm6fhwx-python 
  janus-idp.io/tekton: ponm6fhwx-python
  backstage.io/kubernetes-id: ponm6fhwx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ponm6fhwx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml