apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ponm6fhwx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ponm6fhwx-python 
  name: ponm6fhwx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ponm6fhwx-python 
